### PR TITLE
CI: perform `set-refresh-dirs`

### PR DESCRIPTION
**Pull request by vemv**
## Brief

Fixes the build broken in 87af50a8b6febdbcaa6c9908905c1e3c6024282e

Uses an approach outlined in the Lein template that this project uses.

#### Note

* Running the test suite from a repl/ide will pass, since a dev environment has the `refresh-dirs` set via dev.clj
* `lein test` or `lein with-profile -dev test` performed locally will keep failing, because `CI` is unset
  * That can be fixed by preceding the command with `CI=1`.
  * It also could be fixed in a manner similar to https://github.com/nedap/formatting-stack/issues/167#issuecomment-802047785

## QA plan

`CI=true lein with-profile -user,-dev do clean, test` should pass

## Author checklist

* [x] I have QAed the functionality
* [x] The PR has a reasonably reviewable size and a meaningful commit history
* [x] I have run the [branch formatter](https://github.com/nedap/formatting-stack/blob/332a419034ab46fad526a5592f4257353bd695b6/src/formatting_stack/branch_formatter.clj) and observed no new/significative warnings
* [x] The build passes
* [x] I have self-reviewed the PR prior to assignment
* Additionally, I have code-reviewed iteratively the PR considering the following aspects in isolation:
  * [x] Correctness
  * [x] Robustness (red paths, failure handling etc)
  * [x] Test coverage
  * [x] Spec coverage
  * [x] Documentation
  * [x] Security
  * [x] Performance
  * [x] Breaking API changes
  * [x] Cross-compatibility (Clojure/ClojureScript)

## Reviewer checklist

* [ ] I have checked out this branch and reviewed it locally, running it
* [ ] I have QAed the functionality
* [ ] I have reviewed the PR
* Additionally, I have code-reviewed iteratively the PR considering the following aspects in isolation:
  * [ ] Correctness
  * [ ] Robustness (red paths, failure handling etc)
  * [ ] Test coverage
  * [ ] Spec coverage
  * [ ] Documentation
  * [ ] Security
  * [ ] Performance
  * [ ] Breaking API changes
  * [ ] Cross-compatibility (Clojure/ClojureScript)

### CODE REVIEW

**Comment by thumbnail** [comment]
> It also could be fixed in a manner similar to https://github.com/nedap/formatting-stack/issues/167#issuecomment-802047785

Why is it desirable not to fix this issue locally?

**Comment by vemv** [comment]
> Why is it desirable not to fix this issue locally?

Because the proposed `(set-refresh-dirs "src" "test")` would easily conflict with that defined in dev.clj, which would lead to opaque issues

(Note that `locally` is a bit more broader than reality; running tests from the repl will work)

**Comment by vemv** [comment]
...perhaps we can change it to

```clj
(when-not (seq refresh-dirs)
  (set-refresh-dirs "src" "test"))
```

I wouldn't like it 100%, but it's not fragile either and would fix `lein test`

**Comment by thumbnail** [comment]
That sounds like a good idea!

**Comment by vemv** [comment]
Thanks! Ready

image

**Pull request merged**
