### PR TITLE
[WIP] Mount integration

### PR DESCRIPTION
**Pull request by vemv**
## Brief

Continues https://github.com/nedap/formatting-stack/pull/127

cc/ @DarinDouglass

## Author checklist

* [ ] I have QAed the functionality
* [ ] The PR has a reasonably reviewable size and a meaningful commit history
* [ ] I have run the [branch formatter](https://github.com/nedap/formatting-stack/blob/332a419034ab46fad526a5592f4257353bd695b6/src/formatting_stack/branch_formatter.clj) and observed no new/significative warnings
* [ ] The build passes
* [ ] I have self-reviewed the PR prior to assignment
* Additionally, I have code-reviewed iteratively the PR considering the following aspects in isolation:
  * [ ] Correctness
  * [ ] Robustness (red paths, failure handling etc)
  * [ ] Modular design
  * [ ] Test coverage
  * [ ] Spec coverage
  * [ ] Documentation
  * [ ] Security
  * [ ] Performance
  * [ ] Breaking API changes
  * [ ] Cross-compatibility (Clojure/ClojureScript)

## Reviewer checklist

* [ ] I have checked out this branch and reviewed it locally, running it
* [ ] I have QAed the functionality
* [ ] I have reviewed the PR
* Additionally, I have code-reviewed iteratively the PR considering the following aspects in isolation:
  * [ ] Correctness
  * [ ] Robustness (red paths, failure handling etc)
  * [ ] Modular design
  * [ ] Test coverage
  * [ ] Spec coverage
  * [ ] Documentation
  * [ ] Security
  * [ ] Performance
  * [ ] Breaking API changes
  * [ ] Cross-compatibility (Clojure/ClojureScript)

### CODE REVIEW

**Comment by vemv** [comment]
I extended the `mount-repl` example so that I could verify if the 2 suggested ways of using Mount can be toggled.

It didn't seem the case - here's my REPL session:

```clj
mount-repl> (formatting-stack.mount/configure! {:linters        sample-linters-1
                                                :in-background? false})
{:formatting-with-mount-args #function[clojure.core/partial/fn--5841], :formatting-with-provided-config #function[clojure.core/partial/fn--5841]}
mount-repl> (mount.core/start)
path.clj
  :mount-repl/foo-linter
    6:40 Hello, I am Linter 1!

1 warnings found
{:started ["#'functional.formatting-stack.mount/stateful-component"]}
mount-repl> (mount.core/start-with-args
             {:formatting-stack.mount/config {:linters        sample-linters-2
                                              :in-background? false}})
path.clj
  :mount-repl/foo-linter
    6:40 Hello, I am Linter 1!

1 warnings found
path.clj
  :mount-repl/bar-linter
    6:40 Hello, I am Linter 2!

1 warnings found
{:started []}
mount-repl> (mount.core/start)
path.clj
  :mount-repl/foo-linter
    6:40 Hello, I am Linter 1!

1 warnings found
path.clj
  :mount-repl/bar-linter
    6:40 Hello, I am Linter 2!

1 warnings found
{:started []}
mount-repl> (formatting-stack.mount/configure! {:linters        sample-linters-1
                                                :in-background? false})
{:formatting-with-mount-args #function[clojure.core/partial/fn--5841], :formatting-with-provided-config #function[clojure.core/partial/fn--5841]}
mount-repl> (mount.core/start)
path.clj
  :mount-repl/foo-linter
    6:40 Hello, I am Linter 1!

1 warnings found
path.clj
  :mount-repl/bar-linter
    6:40 Hello, I am Linter 2!

1 warnings found
{:started []}
mount-repl> (mount.core/start)
path.clj
  :mount-repl/foo-linter
    6:40 Hello, I am Linter 1!

1 warnings found
path.clj
  :mount-repl/bar-linter
    6:40 Hello, I am Linter 2!

1 warnings found
{:started []}
mount-repl> 
formatting-stack.mount> 
mount-repl> 
```

The problem being, once `Linter 2` is printed, there's nothing I can do in order to get rid of iit.

I would expect instead that either I see `Linter 1` or `Linter 2`, but not both. Or at least have a way to clean up the state so one can start from scratch.

WDYT? @DarinDouglass

**Comment by DarinDouglass** [comment]
Hmm, interesting. Only real thought at the moment is that adding hooks (`mount-up` is a thin wrapper around `robert/hook`) isn't destructive, event when using keys.

I'll poke around today to see what's going on.

**Comment by DarinDouglass** [comment]
Ok so I took some time to process the flow there.

At the moment there is no real dependency/link between the two forms of `mount` configuring. They can and do work completely independently.

So your flow is as such:

1) On `formatting-stack.mount` load, you configure the `mount/args`
2) You `configure!` the first linter, which shows up as expected on the first `mount/start` call.
3) You run `mount/start-with-args` with the second linter which "enables" the hook created in step `. The linter shows up as expected.
4) You "re-configure!" the parametered version of the hook to use the first linter. This doesn't actually do anything give it was _already_ configured with the first linter.
5) Since you have not cleared `mount/args` the second linter continues to run.

The easiest way to get rid of what you're seeing is run another `mount/start-with-args` call with an empty `{}` this time.

---

I'm not sure this behavior (`mount/args` vs explicit config) is super great, given it can lead some seemingly odd behavior for people who don't use `mount` much.

Given `formatting-stack` is a development-focused tool and by making some (large) assumptions of the general use-patterns of `mount`, I think dropping the `mount/args` configuration point would be the easiest fix here.

**Comment by DarinDouglass** [comment]
That leaves the `mount` namespace to basically just be:

```clj
(defn configure! [config]
  (mount-up/on-up :formatting #(start config) :before))
```

**Comment by vemv** [comment]
Sounding great! Thanks for the explanations.

Can you try out the described changes and PR them against this `126--mount` branch?

Immediately thereafter I'll release an `alpha` so that you can consume it for a few days. Following that, we'd get this PR into master.

**Comment by DarinDouglass** [comment]
[PR is up.](https://github.com/nedap/formatting-stack/pull/135)

**Comment by thumbnail** [comment]
@DarinDouglass Thanks, I've bumped the version, when it's done building a release should be available on clojars

**Comment by vemv** [comment]
Today we released the general-purpose `4.0.1` with various bugfixes.

I just also released `4.1.0-alpha2` which has those + Mount, in case it eases QAing.

Let us know if it's working well for you - would appreciate any kind of feedback of course.

**Comment by DarinDouglass** [comment]
I'll poke around and see how it feels!

**Comment by vemv** [comment]
Closing for the time being, we have various refactorings in mind so advanding on this PR would mean more merge conflicts / breaking changes.

**Pull request closed without merging**
